---
title: "Automated Speed Checker"
author: "Eidan Jacob"
date: "July 13, 2018"
output: html_document
---

## Speed Checking
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, warning = FALSE, message = FALSE)
library(readr)
library(dplyr)
library(sp)
library(rgdal)
library(lubridate)
library(raster)
library(deldir)
library(geosphere)
library(rgeos)
```

Define files to check & limit (m/s):
```{r}
files <- paste0("../data-plus-2018_wireless-ap-logs_201804", as.character(18:30), ".csv")
limit <- 10
```

Read coordinate data and calculate adjacency matrix for locations to reduce false positive rates.
```{r}
coord <- read_csv("../locationsToCoordinates.csv")
validLocations <- read_csv("../allAPs.csv")
validLocations$ap <- validLocations$APname
validLocations <- merge(coord, validLocations) # link coordinates to locations

transTable <- data.frame("macaddr" = NULL, "location" = NULL, "arrival" = NULL, "departure" = NULL)
lastMention <- data.frame("macaddr" = NULL, "row" = NULL)

# Transition Table
for(f in files){
  # Read in a file.
  data <- read_csv(f)
  data <- merge(data, validLocations)
  # Get list of macs mentioned in this file.
  macs <- unique(data$macaddr)
  macs <- macs[!is.na(macs)]
  # For each mac:
  for(mac in macs){
    # Filter out all of its events.
    sub <- data %>% filter(macaddr == mac)
    
    if(!(mac %in% lastMention$macaddr)){
      # If we haven't seeen this mac before, add it to lastMention table + transTable
      newRow <- data.frame("macaddr" = mac, "row" = nrow(transTable)+1)
      lastMention <- cbind(lastMention, newRow)
      newRow <- data.frame("macaddr" = mac, "location" = sub$location.y[1], 
                           "arrival" = sub$`_time`[1], "departure" = sub$`_time`[1])
      transTable <- cbind(transTable, newRow)
    }
    
    # ... find the last row we have on it...
    lastRow <- lastMention$row[lastMention$macaddr == mac]
    # ... and the last location it was in.
    lastLoc <- transTable$location[lastRow]
    # Then for each event, update the table:
    for(i in nrow(sub)){
      # If the next event is in the same location...
      if(sub$location.y == lastLoc){
        # Just push back the departure time.
        transTable$departure[lastRow] <- sub$`_time`[i]
      } else{
      # If the next event is in a different location, update both tables
        newRow <- data.frame("macaddr" = mac, "row" = nrow(transTable)+1)
        lastMention <- cbind(lastMention, newRow)
        newRow <- data.frame("macaddr" = mac, "location" = sub$location.y[i],
                             "arrival" = sub$`_time`[i], "depature" = sub$`_time`[i])
        transTable <- cbind(transTable, newRow)
      }
    }
  }
}
# calculating voronoi cells and converting to polygons to plot on map
z <- deldir(coord$long, coord$lat) # computes cells
# convert cell info to spatial data frame (polygons)
w <- tile.list(z)
polys <- vector(mode="list", length=length(w))
for (i in seq(along=polys)) {
  pcrds <- cbind(w[[i]]$x, w[[i]]$y)
  pcrds <- rbind(pcrds, pcrds[1,])
  polys[[i]] <- Polygons(list(Polygon(pcrds)), ID=as.character(i))
}
SP <- SpatialPolygons(polys)
for(x in 1:nrow(coord)){
  SP@polygons[[x]]@ID <- as.character(x)
}
SPDF <- SpatialPolygonsDataFrame(SP, data=data.frame(x=coord[,2], y=coord[,3]))
# tag polygons with location name
SPDF@data$ID = coord$location
a <- sapply(1:length(coord$location), function(x){
  SPDF@polygons[[x]]@ID <- coord$location[x]
  SPDF <<- SPDF
})
adjTable <- gTouches(SPDF, byid = TRUE)
```

Distance table:
```{r}
# disTable <- sapply(coord$location, function(location){
#   c1 <- c(coord$lat[coord$location == location], coord$long[coord$location == location])
#   sapply(1:nrow(coord), function(i){
#     distHaversine(c1, coord[i,c("lat", "long")])
#   })
# })
# rownames(disTable) <- colnames(disTable)
```
